"""
Django settings for servico_de_cozinha_de_restaurante project.
Generated by 'django-admin startproject'.
"""

from pathlib import Path
import os

# Caminho base do projeto
BASE_DIR = Path(__file__).resolve().parent.parent

# Segurança — mantenha a chave secreta em segredo em produção!
SECRET_KEY = 'django-insecure-substitua-esta-chave-por-uma-secreta'

# ⚠️ Modo de desenvolvimento
DEBUG = True

# Libera o acesso local (apenas enquanto estiver desenvolvendo)
ALLOWED_HOSTS = ['*']

# Aplicativos instalados
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'cozinha',

    # 👇 Aqui você adicionará seus apps
    # 'cozinha',  # exemplo de app futuro
]

# Middlewares — controlam requisições/respostas
MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

# Arquivo principal de URLs
ROOT_URLCONF = 'servico_de_cozinha_de_restaurante.urls'

# Configuração dos templates (HTML)
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        # 👇 Aqui o Django vai procurar na pasta principal "templates"
        'DIRS': [BASE_DIR / "templates"],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]


# Arquivo WSGI (usado em servidores)
WSGI_APPLICATION = 'servico_de_cozinha_de_restaurante.wsgi.application'

# Banco de dados padrão (SQLite)
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}

# Validação de senha (padrão Django)
AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Localização e idioma
LANGUAGE_CODE = 'pt-br'
TIME_ZONE = 'America/Sao_Paulo'
USE_I18N = True
USE_TZ = True

# Configuração de arquivos estáticos (CSS, JS, imagens)
STATIC_URL = 'static/'
STATICFILES_DIRS = [BASE_DIR / 'static']

# Arquivos enviados por usuários (ex: fotos de pratos)
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Identificador do tipo de campo padrão para chaves primárias
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
AUTH_USER_MODEL = 'cozinha.Cook'
